
backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Heating", "Cooling", "Ventilation", "Air Quality", "Maintenance", "Emergency", "Energy Efficiency", "Winter Maintenance", "Commercial"]}
      - {label: "Read Time", name: "readTime", widget: "string", default: "5 min read"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "SEO Title", name: "seoTitle", widget: "string", required: false}
      - {label: "SEO Description", name: "seoDescription", widget: "text", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}

  - name: "services"
    label: "Service Pages"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Service Icon", name: "icon", widget: "string", hint: "Emoji or icon class"}
      - {label: "Short Description", name: "shortDescription", widget: "text"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Body Content", name: "body", widget: "markdown"}
      - {label: "Sub Services", name: "subServices", widget: "list", field: {label: "Service", name: "service", widget: "string"}}
      - {label: "Starting Price", name: "startingPrice", widget: "string", required: false}
      - {label: "SEO Title", name: "seoTitle", widget: "string", required: false}
      - {label: "SEO Description", name: "seoDescription", widget: "text", required: false}

  - name: "testimonials"
    label: "Customer Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Customer Name", name: "name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Rating", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5}
      - {label: "Testimonial", name: "text", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Service Type", name: "serviceType", widget: "select", options: ["Heating", "Cooling", "Maintenance", "Emergency", "Installation", "Repair"]}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "team"
    label: "Team Members"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Years Experience", name: "experience", widget: "number", value_type: "int"}
      - {label: "Certifications", name: "certifications", widget: "list", field: {label: "Certification", name: "cert", widget: "string"}}
      - {label: "Specialties", name: "specialties", widget: "list", field: {label: "Specialty", name: "specialty", widget: "string"}}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "src/content/settings/general.yml"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Business Name", name: "businessName", widget: "string"}
          - {label: "Phone Number", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Business Hours", name: "businessHours", widget: "object", fields: [
              {label: "Monday-Friday", name: "weekdays", widget: "string"},
              {label: "Saturday-Sunday", name: "weekends", widget: "string"},
              {label: "Emergency", name: "emergency", widget: "string"}
            ]}
          - {label: "Service Areas", name: "serviceAreas", widget: "list", field: {label: "Area", name: "area", widget: "string"}}
          - {label: "Social Media", name: "social", widget: "object", fields: [
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false},
              {label: "Google Business", name: "google", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
            ]}

      - label: "SEO Settings"
        name: "seo"
        file: "src/content/settings/seo.yml"
        fields:
          - {label: "Default SEO Title", name: "defaultTitle", widget: "string"}
          - {label: "Default SEO Description", name: "defaultDescription", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "list", field: {label: "Keyword", name: "keyword", widget: "string"}}
          - {label: "Google Analytics ID", name: "googleAnalytics", widget: "string", required: false}
          - {label: "Google Tag Manager ID", name: "googleTagManager", widget: "string", required: false}

      - label: "Emergency Banner"
        name: "emergency"
        file: "src/content/settings/emergency.yml"
        fields:
          - {label: "Show Emergency Banner", name: "showBanner", widget: "boolean", default: false}
          - {label: "Banner Message", name: "message", widget: "string"}
          - {label: "Banner Color", name: "color", widget: "select", options: ["red", "orange", "yellow"], default: "red"}
          - {label: "Call to Action Text", name: "ctaText", widget: "string"}
